export const images = {
    userImage: require('../assets/images/user-image.png'),
    image1: require('../assets/images/image-1.png'),
    image2: require('../assets/images/image-2.png'),
    image3: require('../assets/images/image-3.png'),
    image4: require('../assets/images/image-4.png'),
    image5: require('../assets/images/image-5.png'),
    image6: require('../assets/images/image-6.png'),
    image7: require('../assets/images/image-7.png'),
    image8: require('../assets/images/image-8.png'),
    image9: require('../assets/images/image-9.png'),
    image10: require('../assets/images/image-10.png'),
    image11: require('../assets/images/image-11.png'),
    happyBirthday: require('../assets/images/happy-birthday.png'),
    BackgroundImage: require('../assets/images/background.png'),
};
